
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finalSprintDB
    ports:
      - "3307:3306"
    networks:
      - app-network

  myapp-main:
    image: simple-life-backend:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/finalSprintDB
      - spring.datasource.username=root
      - spring.datasource.password=password
    networks:
      - app-network

networks:
  app-network:
