version: '3'
services:
  myapp-main:
    image: simple-life-backend:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/finalSprintDB
      - spring.datasource.password=password
      - spring.datasource.username=root